[package]
name = "namaka"
version = "0.2.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = "Snapshot testing for Nix based on haumea"
readme = "README.md"
homepage = "https://github.com/figsoda/namaka"
repository = "https://github.com/figsoda/namaka"
license = "MPL-2.0"
keywords = ["assert", "cli", "nix", "snapshot", "testing"]
categories = ["command-line-utilities", "development-tools::testing"]

[dependencies]
bstr = "1.7.0"
color-eyre = "0.6.2"
dialoguer = "0.11.0"
eyre = "0.6.8"
monostate = "0.1.9"
owo-colors = "3.5.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
similar = { version = "2.3.0", features = ["unicode"] }
toml = "0.8.3"

[dependencies.bat]
version = "0.24.0"
default-features = false
features = ["regex-onig"]

[dependencies.clap]
version = "4.4.6"
features = ["cargo", "derive", "unicode", "wrap_help"]

[build-dependencies]
clap = { version = "4.4.6", features = ["derive", "string"] }
clap_complete = "4.4.3"
clap_mangen = "0.2.14"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
